name: Publish Android release
on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2.16.0
        with:
#          flutter-version: '3.16.5'
          dart-version: '3.3.0'  # Added Dart SDK version
          cache: true      
      - name: Get dependencies
        run: flutter pub get
      - name: Build APK
        working-directory: .
        run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk