name: Publish Android release
on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      # Get flutter packages
      - run: flutter pub get
      # Build :D 
      - run: flutter build apk